[tool.poetry]
name = "pg-es-fdw"
version = "0.7.3"
description = "Connect PostgreSQL and Elastic Search with this Foreign Data Wrapper"
authors = ["Matthew Franglen <matthew@franglen.org>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/matthewfranglen/postgres-elasticsearch-fdw"
repository = "https://github.com/matthewfranglen/postgres-elasticsearch-fdw"
keywords = ["postgresql", "postgres", "elasticsearch", "es", "fdw"]

[tool.poetry.urls]
download ="https://github.com/matthewfranglen/postgres-elasticsearch-fdw/archive/0.7.3.zip"

[tool.poetry.dependencies]
elasticsearch = "^7.6.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
pylint = "^2.4.4"
pytest = "^5.4.1"
sh = "^1.12.14"
docker-compose = "^1.25.4"
psycopg2 = "^2.8.5"
ipython = "^7.13.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
